spring:
  datasource:
    name: abc  #数据库名
    url: jdbc:mysql://localhost:3306/abc?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8 #url
    username: root  #用户名
    password: 1234  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动

mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.example.test.bean #配置实体类